
var toaletter = [
    {
        "herre": 1,
        "dame": 1,
        "rullestol": 1,
        "stellerom": "NULL",
        "pris": 12,
        "adresse": "Lungegårdskaien",
        "plassering": "NONNESETER TERMINAL, SØR",
        "place": "NONNESETER TERMINAL, SOUTH",
        "tid_hverdag": "07.00 - 23.15",
        "tid_lordag": "07.00 - 23.15",
        "tid_sondag": "07.00 - 23.15",
        "pissoir_only": "NULL",
        "id": "1",
        "latitude": "60.3879681",
        "longitude": "5.334608"
    },
    {
        "herre": 1,
        "dame": 1,
        "rullestol": 1,
        "stellerom": "NULL",
        "pris": 12,
        "adresse": "Østre Strømkai",
        "plassering": "NONNESETER TERMINAL , NORD",
        "place": "NONNESETER TERMINAL , NORTH",
        "tid_hverdag": "05.30 - 23.50",
        "tid_lordag": "07.00 - 23.15",
        "tid_sondag": "NULL",
        "pissoir_only": "NULL",
        "id": "2",
        "latitude": "60.3884988",
        "longitude": "5.3345382"
    },
    {
        "herre": 1,
        "dame": 1,
        "rullestol": 1,
        "stellerom": "NULL",
        "pris": 12,
        "adresse": "Østre Strømkai",
        "plassering": "SKYSS KUNDESENTER",
        "place": "SKYSS CUSTOMER CENTRE",
        "tid_hverdag": "09.00 - 17.00",
        "tid_lordag": "09.00 - 15.00",
        "tid_sondag": "NULL",
        "pissoir_only": "NULL",
        "id": "3",
        "latitude": "60.388868",
        "longitude": "5.3337597"
    },
    {
        "herre": 1,
        "dame": 1,
        "rullestol": "NULL",
        "stellerom": "NULL",
        "pris": 10,
        "adresse": "Strømgaten 4",
        "plassering": "JERNBANESTASJONEN",
        "place": "RAILWAY STATION",
        "tid_hverdag": "07.00 - 23.00",
        "tid_lordag": "07.00 - 23.00",
        "tid_sondag": "07.00 - 23.00",
        "pissoir_only": "NULL",
        "id": 4,
        "latitude": "60.39041",
        "longitude": "5.332995"
    },
    {
        "herre": 1,
        "dame": 1,
        "rullestol": 1,
        "stellerom": 1,
        "pris": 10,
        "adresse": "Strandkaien 3",
        "plassering": "MATHALLEN",
        "place": "FISH MARKET",
        "tid_hverdag": "09.00 - 23.00",
        "tid_lordag": "08.30 - 22.00",
        "tid_sondag": "08.30 - 22.00",
        "pissoir_only": "NULL",
        "id": "5",
        "latitude": "60.394554",
        "longitude": "5.324099"
    },
    {
        "herre": 1,
        "dame": 1,
        "rullestol": "NULL",
        "stellerom": "NULL",
        "pris": 10,
        "adresse": "Strandkaien",
        "plassering": "STRANDKAITERMINALEN",
        "place": "STRANDKAI BOAT TERMINAL",
        "tid_hverdag": "08.00 - 18.00",
        "tid_lordag": "08.00 - 18.00",
        "tid_sondag": "08.00 - 18.00",
        "pissoir_only": "NULL",
        "id": "6",
        "latitude": "60.3951003",
        "longitude": "5.3220606"
    },
    {
        "herre": 1,
        "dame": 1,
        "rullestol": 1,
        "stellerom": "NULL",
        "pris": 0,
        "adresse": "Kaigaten 4",
        "plassering": "BERGEN KOMMUNE, INNBYGGERSERVICE",
        "place": "CITIZEN SERVICE CENTRE",
        "tid_hverdag": "08.00 - 15.00",
        "tid_lordag": "NULL",
        "tid_sondag": "NULL",
        "pissoir_only": "NULL",
        "id": "7",
        "latitude": "60.3913793",
        "longitude": "5.3290558"
    },
    {
        "herre": 1,
        "dame": 1,
        "rullestol": 1,
        "stellerom": 1,
        "pris": 10,
        "adresse": "Strømgaten 8",
        "plassering": "BERGEN STORSENTER",
        "place": "BERGEN STORSENTER",
        "tid_hverdag": "09.00 - 21.00",
        "tid_lordag": "09.00 - 18.00",
        "tid_sondag": "NULL",
        "pissoir_only": "NULL",
        "id": "8",
        "latitude": "60.3891105",
        "longitude": "5.3322315"
    },
    {
        "herre": 1,
        "dame": 1,
        "rullestol": 1,
        "stellerom": 1,
        "pris": 10,
        "adresse": "Torgallmenningen 14",
        "plassering": "SUNDT MOTEHUS",
        "place": "SUNDT FASHION HOUSE",
        "tid_hverdag": "09.00 - 21.00",
        "tid_lordag": "09.00 - 18.00",
        "tid_sondag": "NULL",
        "pissoir_only": "NULL",
        "id": "9",
        "latitude": "60.392209",
        "longitude": "5.324011"
    },
    {
        "herre": 1,
        "dame": 1,
        "rullestol": 1,
        "stellerom": 1,
        "pris": 10,
        "adresse": "Småstrandgaten 3",
        "plassering": "XHIBITION",
        "place": "XHIBITION",
        "tid_hverdag": "09.00 - 20.00",
        "tid_lordag": "09.00 - 18.00",
        "tid_sondag": "NULL",
        "pissoir_only": "NULL",
        "id": "10",
        "latitude": "60.3927098",
        "longitude": "5.3262019"
    },
    {
        "herre": 1,
        "dame": 1,
        "rullestol": 1,
        "stellerom": 1,
        "pris": 10,
        "adresse": "Torgallmenningen 8",
        "plassering": "GALLERIET",
        "place": "GALLERIET",
        "tid_hverdag": "09.00 - 21.00",
        "tid_lordag": "09.00 - 18.00",
        "tid_sondag": "NULL",
        "pissoir_only": "NULL",
        "id": "11",
        "latitude": "60.3932345",
        "longitude": "5.3252363"
    },
    {
        "herre": 1,
        "dame": 1,
        "rullestol": 1,
        "stellerom": 1,
        "pris": 10,
        "adresse": "Strandgaten 13 -15",
        "plassering": "KLØVERHUSET",
        "place": "KLØVERHUSET",
        "tid_hverdag": "10.00 - 20.00",
        "tid_lordag": "10.00 - 18.00",
        "tid_sondag": "NULL",
        "pissoir_only": "NULL",
        "id": "12",
        "latitude": "60.3944194",
        "longitude": "5.3205649"
    },
    {
        "herre": 1,
        "dame": 1,
        "rullestol": 1,
        "stellerom": "NULL",
        "pris": 10,
        "adresse": "Jacobsfjorden, Bryggen",
        "plassering": "BRYGGEN BESØKSSENTER",
        "place": "BRYGGEN VISITOR CENTRE",
        "tid_hverdag": "09.00 - 18.00",
        "tid_lordag": "09.00 - 18.00",
        "tid_sondag": "09.00 - 18.00",
        "pissoir_only": "NULL",
        "id": "13",
        "latitude": "60.3975913",
        "longitude": "5.3244317"
    },
    {
        "herre": "NULL",
        "dame": "NULL",
        "rullestol": "NULL",
        "stellerom": "NULL",
        "pris": "NULL",
        "adresse": "C. Sundts gt",
        "plassering": "C. SUNDTSGT",
        "place": "C. SUNDTSGT",
        "tid_hverdag": "ALL",
        "tid_lordag": "ALL",
        "tid_sondag": "ALL",
        "pissoir_only": "1",
        "id": "14",
        "latitude": "60.3973581",
        "longitude": "5.3132629"
    }
]

